/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.d.ts` (hash: 1ea5c5f9f6833b304189f1231c9c8df7)
interface __BaseEnv_Env {
	DOCS: KVNamespace;
	REVIEWS: D1Database;
	UPLOAD_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.txt" {
	const value: string;
	export default value;
}